### ISSUE TITLE
Using mysqldump.

### ISSUE THREAD

**Issue by boycce** [josephspurrier/surfstack-wamp#4]
Are we still able to use mysqldump under `../amp/app/mysql/bin/mysqldump.exe` ?
Dumping out my database with `mysqldump -u root --no-data my_db` yields this error:

> mysqldump: Can't read dir of '/etc/mysql/conf.d/' (Errcode: 2 - No such file or directory)
> Fatal error in defaults handling. Program aborted

Cheers.

**Comment by boycce** [comment]
Yay, I managed to get it working by referencing `php.ini` through `--defaults-file`. Note, the precedence of the argument is important.

 ```
mysqldump.exe --defaults-file=../my.ini -u root my_db
```

I can imagine this answer is not just limited to surfstack-wamp ;)

**Comment by josephspurrier** [comment]
Nice find. I'm sure this will help out others that are using it.
